name: Build and deploy Node.js app to Azure Web App - TrelloNext

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Run tests (if present)
        run: npm run test --if-present

      - name: Install production dependencies only
        run: npm ci --omit=dev

      - name: Zip project for deployment
        run: |
          zip -r release.zip . -x "*.git*" -x "tests/*" -x "*.github*" -x "node_modules/.cache/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4224605585434F608AC745BE312073E7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_233E1AFCEF2F43A28E6E8363273B507B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EA2C0A30CC664E1281EA19E387073771 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TrelloNext'
          slot-name: 'Production'
          package: .
